mqmanager/urls.py
from django.conf.urls import url, include, handler404, handler500
from .views import dashboard, page_not_found, page_error, permission_denied

# from django.contrib import admin
urlpatterns = [
    # dashboard
    url(r'^$', dashboard, name='dashboard'),

    # mq
    url(r'^mq/', include("rabbitmq.urls")),
    url(r'^users/', include("users.urls")),
]

handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

rabbitmq/urls.py
from django.conf.urls import url
from .views import *

app_name = 'mq'

urlpatterns = [
    # cluster
    url(r'^cluster/list$', cluster_list, name='cluster-list'),

    # vhosts
    url(r'^vhost/list$', vhost_list, name='vhost-list'),
    url(r'^vhost/add$', vhost_create, name='vhost-add'),
    url(r'^vhost/delete$', vhost_delete, name='vhost-delete'),

    # permission
    url(r'^permission/list$', permission_list, name='permission-list'),
    url(r'^permission/add$', permission_create, name='permission-add'),
    url(r'^permission/delete$', permission_delete, name='permission-delete'),

    # queue
    url(r'^queue/list$', queue_list, name='queue-list'),
    url(r'^queue/add$', queue_create, name='queue-add'),
    url(r'^queue/delete$', queue_delete, name='queue-delete'),
    url(r'^queue/detail$', queue_detail, name='queue-detail'),

    # exchange
    url(r'^exchange/list$', exchange_list, name='exchange-list'),
    url(r'^exchange/add$', exchange_create, name='exchange-add'),
    url(r'^exchanges/delete$', exchange_delete, name='exchange-delete'),

    # binding
    url(r'^exchanges/bindings/list$', binding_list, name='binding-list'),
    url(r'^exchange/bindings/add$', binding_create, name='binding-add'),
    url(r'^exchange/bindings/delete$', binding_delete, name='binding-delete'),

    # definitions
    url(r'^definitions/sync$', definitions_sync, name='definitions-sync'),
    url(r'^definitions/export$', definitions_export, name='definitions-export'),

    # audit log
    url(r'^audit$', audit_log, name='audit-log'),

    # queue for cluster
    url(r'^queue/cluster/sync', queue_cluster_sync, name='queue-cluster-sync'),
]

users/urls.py
from django.conf.urls import url
from .views import *

app_name = 'users'

urlpatterns = [
    # Login
    url(r'^login$', user_login, name='user-login'),
    url(r'^logout$', user_logout, name='user-logout'),

    # User
    url(r'^user$', user_list, name='user-list'),
    url(r'^user/create$', user_create, name='user-create'),
    url(r'^user/delete', user_delete, name='user-delete'),
    #url(r'^user/delete$', user_logout, name='user-list'),

    # Profile
    url(r'^profile/$', user_profile, name='user-profile'),
]

rabbitmq/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import uuid
import datetime
# Create your models here.


class Auditlog(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    logtime = models.DateTimeField(auto_now_add=True, verbose_name='操作时间')
    user = models.CharField(max_length=128, verbose_name='操作人')
    cluster = models.CharField(max_length=128,null=True, verbose_name='MQ集群')
    type = models.CharField(max_length=128, null=True, verbose_name='类型')
    target = models.CharField(max_length=128, null=True, verbose_name='对象')
    url = models.CharField(max_length=128, null=True, verbose_name='URL')
    method = models.CharField(max_length=128, null=True, verbose_name='参数')
    data = models.CharField(max_length=128, null=True, verbose_name='数据')
    comment = models.TextField(max_length=200, null=True,verbose_name='备注')

    def __str__(self):
        return self.url

    class Meta:
        ordering = ['-logtime']

rabbitmq/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse
from django.http import StreamingHttpResponse
from mqmanager.settings import rabbitmq_list, DATA_TMP_DIR
from .utils import batch_exec
from django.contrib.auth.decorators import login_required
from mqmanager.common import require_role, ServerError
from models import Auditlog
import json


@require_role(role='user')
def cluster_list(request):
    app, action = "MQ集群", "集群列表"
    mq_cluster = rabbitmq_list
    return render(request, 'rabbitmq/cluster_list.html', locals())


@require_role(role='user')
def vhost_list(request):
    app, action = "虚拟主机", "虚拟主机列表"
    vhost_obj = batch_exec()
    vhost_list = vhost_obj.list_vhosts()
    return render(request, 'rabbitmq/vhost_list.html', locals())


@require_role(role='admin')
def vhost_create(request):
    app, action = "虚拟主机", "创建虚拟主机"
    r_data = request.POST
    mq_clusters_list = {k: v['name'] for k, v in rabbitmq_list.items()}
    if request.method == 'POST':
        vhost = r_data.get('vhost', '').strip()
        cluster = r_data.getlist('cluster', '')
        try:
            if '' in [vhost, cluster]:
                error = '带*内容不能为空'
                raise ServerError(error)
        except:
            pass
        else:
            obj = batch_exec(cluster)
            messages = obj.create_vhost(vhost)
            Auditlog.objects.create(user=request.user, type='创建', cluster=json.dumps(r_data.getlist('cluster', '')),
                                    target=app,
                                    url=request.get_full_path(),
                                    method=request.method, data=json.dumps({'vhost': vhost}))
    return render(request, 'rabbitmq/vhost_create.html', locals())


@require_role(role='admin')
def vhost_delete(request):
    app, action = "虚拟主机", "删除虚拟主机"
    r_data = request.GET
    obj = batch_exec(r_data['cluster'])
    obj.delete_vhost(r_data['vhost'])
    Auditlog.objects.create(user=request.user, type='删除', cluster=r_data['cluster'], target=app,
                            url=request.get_full_path(),
                            method=request.method, data={'vhost': r_data['vhost']})
    return HttpResponse(200)


@require_role(role='user')
def permission_list(request):
    app, action = "虚拟主机", "虚拟主机权限列表"
    r_data = request.GET
    obj = batch_exec(request.GET['cluster'])
    permission_list = obj.list_permission(r_data['vhost'])
    return render(request, 'rabbitmq/permission_list.html', locals())


@require_role(role='admin')
def permission_create(request):
    app, action = "虚拟主机权限", "创建虚拟主机权限"
    f_data = request.GET
    obj = batch_exec(f_data['cluster'])
    user_list = obj.list_users()
    if request.method == 'POST':
        r_data = request.POST
        data = {"vhost": r_data['vhost'], "username": r_data['user'], "configure": r_data['configure'],
                "write": r_data['write'], "read": r_data['read']}
        messages = obj.create_permission(vhost=r_data['vhost'], user=r_data['user'], data=data)
        Auditlog.objects.create(user=request.user, type='创建', cluster=f_data['cluster'], target=app,
                                url=request.get_full_path(),
                                method=request.method, data=data)
    return render(request, 'rabbitmq/permission_create.html', locals())


@require_role(role='admin')
def permission_delete(request):
    app, action = "虚拟主机权限", "删除虚拟主机权限"
    r_data = request.GET
    obj = batch_exec(r_data['cluster'])
    data = {"username": r_data['username'], "vhost": r_data['vhost']}
    obj.delete_permission(r_data['vhost'], username=r_data['username'], data=data)
    Auditlog.objects.create(user=request.user, type='删除', cluster=r_data['cluster'], target=app,
                            url=request.get_full_path(),
                            method=request.method, data=data)
    return HttpResponse(200)


@login_required
def user_list(request):
    app, action = "用户", "用户列表"
    return True


@require_role(role='user')
def exchange_list(request):
    app, action = "交换机", "交换机列表"
    exchange_obj = batch_exec()
    exchange_list = exchange_obj.list_exchanges()
    return render(request, 'rabbitmq/exchange_list.html', locals())


@require_role(role='admin')
def exchange_create(request):
    app, action = "交换机", "创建交换机"
    mq_clusters_list = {k: v['name'] for k, v in rabbitmq_list.items()}
    obj = batch_exec()
    vhost_distinct = list(set([j['name'] for i in obj.list_vhosts() for k, v in i.items() for j in v]))
    if request.method == 'POST':
        mq_clusters_selectd = request.POST.getlist('cluster', '')
        f_data = request.POST
        try:
            if '' in [mq_clusters_selectd, f_data['name']]:
                error = '带*内容不能为空'
                raise ServerError(error)
        except:
            pass
        else:
            arguments_list_str = ["alternate-exchange"]
            arguments_dic_str = {k: str(v) for k, v in f_data.items() if k in arguments_list_str and v}
            data = {"vhost": f_data['vhost'], "name": f_data['name'].strip(), "type": f_data['type'],
                    "durable": f_data['durable'],
                    "auto_delete": f_data['auto_delete'], "internal": f_data['internal'],
                    "arguments": arguments_dic_str}
            obj = batch_exec(mq_clusters_selectd)
            messages = obj.create_exchange(vhost=data['vhost'], exchange=data['name'].strip(), data=data)
            Auditlog.objects.create(user=request.user, type='创建', cluster=mq_clusters_selectd, target=app,
                                    url=request.get_full_path(),
                                    method=request.method, data=data)
    return render(request, 'rabbitmq/exchange_create.html', locals())


@require_role(role='user')
def binding_list(request):
    app, action = "交换机绑定", "查看交换机绑定"
    res = request.GET
    obj = batch_exec(res['cluster'])
    binding_list = obj.list_bindings(res['vhost'], res['exchange'])
    return render(request, 'rabbitmq/binding_list.html', locals())


@require_role(role='operator')
def binding_create(request):
    app, action = "交换机绑定", "添加交换机绑定"
    f_data = request.GET
    obj = batch_exec(f_data['cluster'])
    queue_list = obj.list_queues(vhost=f_data['vhost'])[0][f_data['cluster']]
    if request.method == 'POST':
        p_data = request.POST
        try:
            if '' in [p_data['destination'], p_data['routing_key']]:
                error = '带*内容不能为空'
                raise ServerError(error)
        except:
            pass
        else:
            data = {"vhost": p_data['vhost'], "source": p_data['exchange'], "destination_type": p_data['type'],
                    "destination": p_data['destination'], "routing_key": p_data['routing_key'].strip(),
                    "arguments": {}}
            messages = obj.create_binding(vhost=p_data['vhost'], exchange=p_data['exchange'], type=p_data['type'],
                                          destination=p_data['destination'], data=data)
            Auditlog.objects.create(user=request.user, type='创建', cluster=f_data['cluster'], target=app,
                                    url=request.get_full_path(),
                                    method=request.method, data=data)
    return render(request, 'rabbitmq/binding_create.html', locals())


@require_role(role='admin')
def binding_delete(request):
    app, action = "交换机绑定", "删除交换机绑定"
    r_data = request.GET
    obj = batch_exec(r_data['cluster'])
    data = {"vhost": r_data['vhost'], "source": r_data['exchange'], "destination": r_data['destination'],
            "destination_type": r_data['type'], "properties_key": r_data['properties_key']}
    obj.delete_binding(r_data['vhost'], r_data['exchange'], r_data['type'], r_data['destination'],
                       r_data['properties_key'], data=data)
    Auditlog.objects.create(user=request.user, type='删除', cluster=r_data['cluster'], target=app,
                            url=request.get_full_path(),
                            method=request.method, data=data)
    return HttpResponse(200)


@require_role(role='admin')
def exchange_delete(request):
    app, action = "交换机", "删除交换机"
    r_data = request.GET
    obj = batch_exec(r_data['cluster'])
    obj.delete_exchange(r_data['vhost'], r_data['exchange'])
    Auditlog.objects.create(user=request.user, type='删除', cluster=r_data['cluster'], target=app,
                            url=request.get_full_path(),
                            method=request.method, data={'vhost': r_data['vhost'], 'exchange': r_data['exchange']})
    return HttpResponse(200)


@require_role(role='user')
def queue_list(request):
    app, action = "队列", "队列列表"
    cluster_dic = {k: v['name'] for k, v in rabbitmq_list.items()}
    cluster_dic['all'] = "全部集群"
    cluster = request.GET.getlist('cluster', '')
    if cluster == ['all']:
        cluster = [k for k, v in rabbitmq_list.items()]
    obj = batch_exec(cluster)
    queue_list = obj.list_queues()
    return render(request, 'rabbitmq/queue_list.html', locals())


@require_role(role='operator')
def queue_create(request):
    app, action = "消息队列", "创建消息队列"
    mq_clusters_list = {k: v['name'] for k, v in rabbitmq_list.items()}
    obj = batch_exec()
    vhost_distinct = list(set([j['name'] for i in obj.list_vhosts() for k, v in i.items() for j in v]))
    exchange_distinct = set([(j['name'], j['vhost']) for i in obj.list_exchanges() for k, v in i.items() for j in v])
    exchange_distinct_list = [{"name": i[0], "vhost": i[1]} for i in exchange_distinct]

    if request.method == 'POST':
        f_data = request.POST
        arguments_list_str = ["x-dead-letter-exchange", "x-dead-letter-routing-key"]
        arguments_list_int = ["x-message-ttl", "x-expires", "x-max-length"]
        arguments_dic_int = {k: int(v) for k, v in f_data.items() if k in arguments_list_int and v}

templates/rabbitmq/binding_list.html
{% extends '_base_list.html' %}
{% load common_tags %}
{% block help_message %}
    <div class="alert alert-info help-message">
        <p>{{ action }}是 用来查看当前交换机(exchange)绑定的消息队列或者交换机信息。</p>
    </div>
{% endblock %}
{% block table_head %}
    <td align="center">环境</td>
    <td align="center">虚拟主机</td>
    <td align="center">交换机</td>
    <td align="center">目标</td>
    <td align="center">目标类型</td>
    <td align="center">路由键</td>
    <td align="center">参数</td>
    <td align="center">操作</td>
{% endblock %}

{% block table_body %}
    {% for cluster,info in binding_list.items %}
        {% for i in info %}
            <tr>
                <td align="center">{{ cluster }}</td>
                <td align="center">{{ i.vhost }}</td>
                <td align="center">{{ i.source }}</td>
                <td align="center">{{ i.destination }}</td>
                <td align="center">{{ i.destination_type }}</td>
                <td align="center">{{ i.routing_key }}</td>
                <td align="center">{{ i.arguments }}</td>
                <td align="center">
                    <a class="btn btn-xs btn-danger btn_binding_delete {% if request.user.role != 'Admin' %}disabled{% endif %}"
                       data-cluster="{{ cluster }}"
                       data-vhost="{{ i.vhost }}"
                       data-exchange="{{ i.source }}"
                       data-destination="{{ i.destination }}"
                       data-destination_type="{% if i.destination_type == 'queue' %}q{% elif i.destination_type == 'exchange' %}e{% endif %}"
                       data-properties_key="{% if i.routing_key %}{{ i.routing_key }}{% else %}~{% endif %}">
                        删除
                    </a>
                </td>
            </tr>
        {% endfor %}
    {% endfor %}
{% endblock %}

{% block custom_foot_js %}
    <script>
        $(document).ready().on('click', '.btn_binding_delete', function () {
            var $this = $(this);
            var cluster = $this.data('cluster');
            var vhost = $this.data('vhost');
            var exchange = $this.data('exchange');
            var destination = $this.data('destination');
            var type = $this.data('destination_type');
            var properties_key = $this.data('properties_key');
            var url = '{% url 'mq:binding-delete'%}?cluster=cluster0000000000&vhost=vhost0000000000&exchange=exchange0000000000&destination=destination0000000000&type=destination_type0000000000&properties_key=properties_key0000000000'.replace("cluster0000000000", cluster).replace("vhost0000000000", vhost).replace("exchange0000000000", exchange).replace("destination0000000000", destination).replace("destination_type0000000000", type).replace("properties_key0000000000", properties_key);
            var content = cluster + '集群的虚拟主机' + vhost + '中的交换机' + exchange + '绑定的队列' + destination + '属性键为' + properties_key
            objectDeleteGet($this, url, content);
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                pageLength: 10,
                responsive: false,
                //dom: '<"html5buttons"B>lTfgitp',
                //dom: '<"html5buttons"B><"top"f>rt<"bottom"pli><"clear">',
                dom: 'Blfrtip',
                bStateSave: true,
                buttons: [
                    {% if request.user.role == 'Operator' %}
                        {
                            text: '添加绑定', action: function (e, dt, button, config) {
                                window.location = '{% url 'mq:binding-add' %}?cluster={{ res.cluster|url_encode }}&vhost={{ res.vhost|url_encode }}&exchange={{ res.exchange|url_encode }}';
                            }
                        },
                    {% endif %}
                    {extend: 'copy', text: '复制到剪贴板'},
                    {extend: 'csv', text: '导出CSV', title: '权限搜索结果'},
                    {extend: 'excel', text: '导出EXCEL', title: '权限搜索结果'},
                ], "oLanguage": { // 国际化配置
                    "sProcessing": "正在获取数据，请稍后...",
                    "sLengthMenu": "显示 _MENU_ 条",
                    "sZeroRecords": "没有找到数据",
                    "sInfo": "从 _START_ 到  _END_ 条记录 总记录数为 _TOTAL_ 条",
                    "sInfoEmpty": "记录数为0",
                    "sInfoFiltered": "(全部记录数 _MAX_ 条)",
                    "sInfoPostFix": "",
                    "sSearch": "搜索",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "第一页",
                        "sPrevious": "上一页",
                        "sNext": "下一页",
                        "sLast": "最后一页"
                    }
                }

            });

        });
    </script>
{% endblock %}

templates/rabbitmq/queue_list.html
{% extends '_base_list.html' %}
{% load common_tags %}
{% block help_message %}
    <div class="alert alert-info help-message">
        <p>{{ action }}是 是指MQ管理平台所管理的所有MQ集群中的消息队列(queue)列表。</p>
        <p>注意：消息队列所对应的集群消费者名称为手动采集，如有缺失信息，请在数据库中补充</p>
    </div>
{% endblock %}
{% block table_head %}
    <td class="text-center">环境</td>
    <td class="text-center">虚拟主机</td>
    <td class="text-center">队列名称</td>
    <td class="text-center">消费集群</td>
    <td class="text-center">消费者</td>
    <td class="text-center">消息总数</td>
    <td class="text-center">操作</td>
{% endblock %}

{% block table_body %}
    {% for i in queue_list %}
        {% for k,v in i.items %}
            {% for j in v %}
                <tr>
                    <td class="text-center">{{ k |env_name }}</td>
                    <td class="text-center">{{ j.vhost }}</td>
                    <td class="text-center">{{ j.name }}</td>
                    <td class="text-center">
                        {% queue_consumers k j.vhost j.name as consumers %}
                        {% for consumer in consumers %}
                            <a class="btn btn-xs {% if consumer == "no_cluster" %} btn-danger {% elif consumer == "no_cached" %} btn-warning{% else %} btn-info{% endif %}">{{ consumer |msg_translate}}</a><br>
                        {% endfor %}
                    </td>
                    <td class="text-center">{{ j.consumers }}</td>
                    <td class="text-center">{{ j.messages }}</td>
                    <td>
                        <a href="{% url 'mq:queue-detail' %}?cluster={{ k }}&vhost={{ j.vhost }}&queue={{ j.name }}"
                           class="btn btn-xs btn-info">详情</a>
                        <a class="btn btn-xs btn-danger btn_queue_delete {% if request.user.role != 'Admin' %}disabled{% endif %}"
                           data-cluster="{{ k }}" data-vhost="{{ j.vhost }}"
                           data-queue="{{ j.name |url_encode }}">删除</a>

                    </td>
                </tr>
            {% endfor %}
        {% endfor %}
    {% endfor %}
{% endblock %}

{% block custom_foot_js %}
    <script>
        $(document).ready().on('click', '.btn_queue_delete', function () {
            var $this = $(this);
            var cluster = $this.data('cluster');
            var vhost = $this.data('vhost');
            var queue = $this.data('queue');
            var url = '{% url 'mq:queue-delete'%}?cluster=cluster0000000000&vhost=vhost0000000000&queue=queue0000000000'.replace("cluster0000000000", cluster).replace("vhost0000000000", vhost).replace("queue0000000000", queue);
            var content = cluster + '集群的虚拟主机:' + vhost + '上的队列:' + queue;
            objectDeleteGet($this, url, content)
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                pageLength: 10,
                responsive: false,
                //dom: '<"html5buttons"B>lTfgitp',
                //dom: '<"html5buttons"B><"top"f>rt<"bottom"pli><"clear">',
                dom: 'Blfrtip',
                bStateSave: true,
                buttons: [
                    {% if request.user.role == 'Admin' or  request.user.role == 'Operator' %}
                        {
                            text: '创建消息队列', action: function (e, dt, button, config) {
                                window.location = '{% url 'mq:queue-add' %}';
                            }
                        },
                    {% endif %}
                    {% for k,v in cluster_dic.items %}
                    {
                        text: '{{ v }}', action: function (e, dt, button, config) {
                            window.location = '{% url 'mq:queue-list' %}?cluster={{ k }}';
                        }
                    },
                    {% endfor %}
                    {extend: 'copy', text: '复制到剪贴板'},
                    {extend: 'csv', text: '导出CSV', title: '消息队列搜索结果'},
                    {extend: 'excel', text: '导出EXCEL', title: '消息队列搜索结果'},
                ], "oLanguage": { // 国际化配置
                    "sProcessing": "正在获取数据，请稍后...",
                    "sLengthMenu": "显示 _MENU_ 条",
                    "sZeroRecords": "没有找到数据",
                    "sInfo": "从 _START_ 到  _END_ 条记录 总记录数为 _TOTAL_ 条",
                    "sInfoEmpty": "记录数为0",
                    "sInfoFiltered": "(全部记录数 _MAX_ 条)",
                    "sInfoPostFix": "",
                    "sSearch": "搜索",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "第一页",
                        "sPrevious": "上一页",
                        "sNext": "下一页",
                        "sLast": "最后一页"
                    }
                }

            });

        });
    </script>
{% endblock %}

templates/rabbitmq/queue_sync.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>MQ管理平台 | 同步队列-集群关系</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">


    <div class="middle-box text-center animated fadeInDown">
        <h1>200</h1>
        <h3 class="font-bold">同步队列与集群对应关系完成</h3>

        <div class="error-desc">
            平台中管理的MQ集群中的队列名称对应的channel消费者IP地址，通过与麒麟平台中的提供的【IP-集群名称】对应关系对应，最终完成MQ的队列名称与麒麟的集群名称的对应。 <br/><a href="{% url 'mq:cluster-list' %}" class="btn btn-primary m-t">返回主页</a>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/static/js/jquery-3.1.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

</body>

</html>

templates/rabbitmq/vhost_list.html
{% extends '_base_list.html' %}
{% load common_tags %}
{% block help_message %}
    <div class="alert alert-info help-message">
        <p>{{ action }}是 是指MQ管理平台所管理的所有MQ集群中的虚拟主机列表。</p>
    </div>
{% endblock %}
{% block table_head %}
    <td class="text-center">环境</td>
    <td class="text-center">vhost</td>
    <td class="text-center">消息Total</td>
    <td class="text-center">消息Ready</td>
    <td class="text-center">消息Unacked</td>
    <td class="text-center">操作</td>
{% endblock %}
{% block table_body %}
    {% for i in vhost_list %}
        {% for k,v in i.items %}
            {% for j in v %}
                {% if j.messages > 5 %}
                    <tr class="text-danger">
                        {% else %}
                    <tr class="text-navy">
                {% endif %}
            <td class="text-center">{{ k|env_name }}</td>
            <td class="text-center">{{ j.name }}</td>
            <td class="text-center">{{ j.messages }}</td>
            <td class="text-center">{{ j.messages_ready }}</td>
            <td class="text-center">{{ j.messages_unacknowledged }}</td>
            <td class="text-center">
                <a href="{% url 'mq:permission-list' %}?cluster={{ k }}&vhost={{ j.name }}"
                   class="btn btn-xs btn-info">查看权限</a>

                <a class="btn btn-xs btn-danger btn_vhost_delete {% if request.user.role != 'Admin' %} disabled{% endif %}"
                   data-cluster="{{ k }}" data-vhost="{{ j.name | url_encode }}">删除</a>
            </td>
            </tr>
            {% endfor %}
        {% endfor %}
    {% endfor %}
{% endblock %}
{% block custom_foot_js %}
    <script>
        $(document).ready().on('click', '.btn_vhost_delete', function () {
            var $this = $(this);
            var cluster = $this.data('cluster');
            var vhost = $this.data('vhost');
            var url = '{% url 'mq:vhost-delete'%}?cluster=cluster0000000000&vhost=vhost0000000000'.replace("cluster0000000000", cluster).replace("vhost0000000000", vhost);
            var content = cluster + '集群的虚拟主机:' + vhost
            objectDeleteGet($this, url, content);
        });
    </script>

    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                pageLength: 10,
                responsive: false,
                //dom: '<"html5buttons"B>lTfgitp',
                //dom: '<"html5buttons"B><"top"f>rt<"bottom"pli><"clear">',
                dom: 'Blfrtip',
                bStateSave: true,
                buttons: [
                    {% if request.user.role == 'Admin' %}
                    {
                        text: '创建虚拟主机', action: function (e, dt, button, config) {
                            window.location = '{% url 'mq:vhost-add' %}';
                        }
                    },
                    {% endif %}
                    {extend: 'copy', text: '复制到剪贴板'},
                    {extend: 'csv', text: '导出CSV', title: '虚拟主机搜索结果'},
                    {extend: 'excel', text: '导出EXCEL', title: '虚拟主机搜索结果'},
                ], "oLanguage": { // 国际化配置
                    "sProcessing": "正在获取数据，请稍后...",
                    "sLengthMenu": "显示 _MENU_ 条",
                    "sZeroRecords": "没有找到数据",
                    "sInfo": "从 _START_ 到  _END_ 条记录 总记录数为 _TOTAL_ 条",
                    "sInfoEmpty": "记录数为0",
                    "sInfoFiltered": "(全部记录数 _MAX_ 条)",
                    "sInfoPostFix": "",
                    "sSearch": "搜索",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "第一页",
                        "sPrevious": "上一页",
                        "sNext": "下一页",
                        "sLast": "最后一页"
                    }
                }

            });

        });
    </script>
{% endblock %}