mqmanager/urls.py
from django.conf.urls import url, include, handler404, handler500
from .views import dashboard, page_not_found, page_error, permission_denied

# from django.contrib import admin
urlpatterns = [
    # dashboard
    url(r'^$', dashboard, name='dashboard'),

    # mq
    url(r'^mq/', include("rabbitmq.urls")),
    url(r'^users/', include("users.urls")),
]

handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

rabbitmq/urls.py
from django.conf.urls import url
from .views import *

app_name = 'mq'

urlpatterns = [
    # cluster
    url(r'^cluster/list$', cluster_list, name='cluster-list'),

    # vhosts
    url(r'^vhost/list$', vhost_list, name='vhost-list'),
    url(r'^vhost/add$', vhost_create, name='vhost-add'),
    url(r'^vhost/delete$', vhost_delete, name='vhost-delete'),

    # permission
    url(r'^permission/list$', permission_list, name='permission-list'),
    url(r'^permission/add$', permission_create, name='permission-add'),
    url(r'^permission/delete$', permission_delete, name='permission-delete'),

    # queue
    url(r'^queue/list$', queue_list, name='queue-list'),
    url(r'^queue/add$', queue_create, name='queue-add'),
    url(r'^queue/delete$', queue_delete, name='queue-delete'),
    url(r'^queue/detail$', queue_detail, name='queue-detail'),

    # exchange
    url(r'^exchange/list$', exchange_list, name='exchange-list'),
    url(r'^exchange/add$', exchange_create, name='exchange-add'),
    url(r'^exchanges/delete$', exchange_delete, name='exchange-delete'),

    # binding
    url(r'^exchanges/bindings/list$', binding_list, name='binding-list'),
    url(r'^exchange/bindings/add$', binding_create, name='binding-add'),
    url(r'^exchange/bindings/delete$', binding_delete, name='binding-delete'),

    # definitions
    url(r'^definitions/sync$', definitions_sync, name='definitions-sync'),
    url(r'^definitions/export$', definitions_export, name='definitions-export'),

    # audit log
    url(r'^audit$', audit_log, name='audit-log'),

    # queue for cluster
    url(r'^queue/cluster/sync', queue_cluster_sync, name='queue-cluster-sync'),
]

users/urls.py
from django.conf.urls import url
from .views import *

app_name = 'users'

urlpatterns = [
    # Login
    url(r'^login$', user_login, name='user-login'),
    url(r'^logout$', user_logout, name='user-logout'),

    # User
    url(r'^user$', user_list, name='user-list'),
    url(r'^user/create$', user_create, name='user-create'),
    url(r'^user/delete', user_delete, name='user-delete'),
    #url(r'^user/delete$', user_logout, name='user-list'),

    # Profile
    url(r'^profile/$', user_profile, name='user-profile'),
]

templates/_app_logo.html
{% load static %}
<li class="nav-header">
    <div class="dropdown profile-element">
        <div href="#" target="_blank">
            <img alt="image" height="55" src="/static/img/logo-mq-text.png" style="margin-left: 10px"/>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="logo-element">
        <img alt="image" height="40" src="/static/img/logo-mq.png"/>
    </div>
</li>

templates/_base_list.html
{% extends 'base.html' %}
{% load static %}
{% block custom_head_css_js %}
    <link href="{% static "css/plugins/datatables/datatables.min.css" %}" rel="stylesheet">
    <link href="{% static 'css/plugins/select2/select2.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static "js/plugins/datatables/datatables.min.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>{% if action %}{{ action }}{% else %}基本数据表格{% endif %}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <!--
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>
                            -->
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            {% block content_left_head %}{% endblock %}
                        <!--
                            {% block table_search %}
                                <form id="search_form" method="get" action=""
                                      class="pull-right mail-search form-inline">
                                    {% block search_form %}
                                        <div class="input-group" style="margin-bottom: 5px">
                                            <input type="text" class="form-control input-sm" name="keyword"
                                                   placeholder="在表格中搜索" value="{{ keyword }}">
                                        </div>
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button id='search_btn' type="submit" class="btn btn-sm btn-primary">
                                                    搜索
                                                </button>
                                            </div>
                                        </div>
                                    {% endblock %}
                                </form>
                            {% endblock %}
                            -->
                            <table class="table table-striped table-bordered table-hover dataTables-example" style="width: 100%";>
                                <thead>
                                <tr>{% block table_head %}{% endblock %}</tr>
                                </thead>
                                <tbody>{% block table_body %}{% endblock %}</tbody>
                            </table>
                            <div class="row">
                                {% block table_pagination %}

                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/_foot_js.html
{% load static %}
<!-- Mainly scripts -->
<script src="{% static "js/plugins/metisMenu/jquery.metisMenu.js" %}"></script>
<script src="{% static "js/plugins/slimscroll/jquery.slimscroll.min.js" %}"></script>

<!-- Toastr -->
<script src="{% static "js/plugins/toastr/toastr.min.js" %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static "js/inspinia.js" %}"></script>
<script src="{% static "js/xxdns.js" %}"></script>
<script src="{% static "js/plugins/dropzone/dropzone.js" %}"></script>
<script src="{% static "js/plugins/pace/pace.min.js" %}"></script>

templates/_foot_js_bak.html
<!-- Mainly scripts -->
<script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/plugins/metisMenu/jquery.metisMenu.js" %}"></script>
<script src="{% static "js/plugins/slimscroll/jquery.slimscroll.min.js" %}"></script>

<!-- Flot -->
<script src="{% static "js/plugins/flot/jquery.flot.js" %}"></script>
<script src="{% static "js/plugins/flot/jquery.flot.tooltip.min.js" %}"></script>
<script src="{% static "js/plugins/flot/jquery.flot.spline.js" %}"></script>
<script src="{% static "js/plugins/flot/jquery.flot.resize.js" %}"></script>
<script src="{% static "js/plugins/flot/jquery.flot.pie.js" %}"></script>

<!-- Peity -->
<script src="{% static "js/plugins/peity/jquery.peity.min.js" %}"></script>
<script src="{% static "js/demo/peity-demo.js" %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static "js/inspinia.js" %}"></script>
<script src="{% static "js/plugins/pace/pace.min.js" %}"></script>

<!-- jQuery UI -->
<script src="{% static "js/plugins/jquery-ui/jquery-ui.min.js" %}"></script>

<!-- GITTER -->
<script src="{% static "js/plugins/gritter/jquery.gritter.min.js" %}"></script>

<!-- Sparkline -->
<script src="{% static "js/plugins/sparkline/jquery.sparkline.min.js" %}"></script>

<!-- Sparkline demo data  -->
<script src="{% static "js/demo/sparkline-demo.js" %}"></script>

<!-- ChartJS-->
<script src="{% static "js/plugins/chartJs/Chart.min.js" %}"></script>

<!-- Toastr -->
<script src="{% static "js/plugins/toastr/toastr.min.js" %}"></script>

<script>
    $(document).ready(function () {
        setTimeout(function () {
            toastr.options = {
                closeButton: true,
                progressBar: true,
                showMethod: 'slideDown',
                timeOut: 2000
            };
            toastr.success('前端页面整理系统', '欢迎登陆');

        }, 1300);
    });
</script>

templates/_footer.html
<div class="footer">
    <div class="pull-right">
        Version <strong>0.0.1-2</strong> GPLv2.
        <img style="display: none" src="#">
    </div>
    <div>
        <strong>Copyright</strong> MQ管理平台 &copy; 2014-2018
    </div>
</div>

templates/_head_css_js.html
{% load static %}
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "font-awesome/css/font-awesome.css" %}" rel="stylesheet">
<script src="{% static "js/jquery-2.1.1.js" %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


<!-- Toastr style -->
<link href="{% static "css/plugins/toastr/toastr.min.css" %}" rel="stylesheet">

<!-- Gritter -->
<link href="{% static "js/plugins/gritter/jquery.gritter.css" %}" rel="stylesheet">


<link href="{% static "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="{% static "css/xxdns.css" %}" rel="stylesheet">

<!-- scripts -->
<link href="{% static "css/plugins/sweetalert/sweetalert.css" %}" rel="stylesheet">
<script src="{% static 'js/plugins/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/plugins/datatables/datatables.min.js' %}"></script>


<!-- Select2 -->
<script src="{% static "js/plugins/select2/select2.full.min.js" %}"></script>
<link href="{% static "css/plugins/select2/select2.min.css" %}" rel="stylesheet">

templates/_header_bar.html
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="输入要搜索的内容..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message">欢迎访问MQ管理平台</span>
            </li>
            {% if request.user.role == 'Admin' %}
            <li class="dropdown">
                <a class="dropdown-toggle count-info" href="{% url 'mq:queue-cluster-sync' %}">
                    <span class="m-r-sm text-muted welcome-message">同步名称</span>
                </a>
            </li>
            {% endif %}
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="m-r-sm text-muted welcome-message">
                        <img alt="image" class="img-circle" width="30" height="30" src="/static/img/avatar/admin.png"/>
                        <span style="font-size: 13px;font-weight: 400"> {{ request.user }}
                            <b class="caret"></b>
                        </span>
                    </span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                    <li><a href="/users/profile"><i class="fa fa-cogs"> </i><span> 查看资料</span></a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{% url 'users:user-logout' %}"><i class="fa fa-sign-out"></i> 注销</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</div>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>{% if app %} {{ app }} {% else %} 应用名称 {% endif %}</h2>
        <ol class="breadcrumb">
        <li>
            <a href="/">仪表盘</a>
        </li>
            <li>
                <a href="#">{% if app %}{{ app }}{% else %}应用名称{% endif %}</a>
            </li>
            <li class="active">
                <strong>{% if action %}{{ action }}{% else %}应用操作{% endif %}</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-2">
    </div>
</div>

templates/_left_side_bar.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            {% include '_app_logo.html' %}
            {% include '_nav.html' %}
        </ul>
    </div>
</nav>

templates/_message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} help-message" >
            {{ message.detail|safe }}
        </div>
    {% endfor %}
{% endif %}

templates/_nav.html
<!-- 仪表盘 -->
<li id="index">
    <a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">仪表盘</span> <span
            class="fa arrow"></span></a>
</li>

<!-- 用户管理 -->
<li id="users">
    <a href="{% url 'users:user-list' %}">
        <i class="fa fa-group" style="font-size: 13px"></i> <span class="nav-label">用户管理</span><span
            class="fa arrow"></span>
    </a>
</li>
<!--应用1-->
<li id="mq" class="active">
    <a href="#"><i class="fa fa-group"></i> <span class="nav-label">集群配置</span> <span
            class="fa arrow"></span></a>
    <ul class="nav nav-second-level active">
        <li><a href="{% url 'mq:cluster-list' %}">集群列表</a></li>
    </ul>
    <ul class="nav nav-second-level">
        <li><a href="{% url 'mq:vhost-list' %}">虚拟主机管理</a></li>
    </ul>
    <ul class="nav nav-second-level">
        <li><a href="{% url 'mq:exchange-list' %}">交换机管理</a></li>
    </ul>
    <ul class="nav nav-second-level">
        <li><a href="{% url 'mq:queue-list' %}">消息队列管理</a></li>
    </ul>
    <ul class="nav nav-second-level">
        <li><a href="{% url 'mq:audit-log' %}">应用操作日志</a></li>
    </ul>
</li>

templates/_pagination.html
<!--内容需要更新加上模板标签才可用 -->
{#% load common_tags %#}
{% if 1 %}
    <div class="col-sm-4">
        <div class="dataTables_info text-center" id="editable_info" role="status" aria-live="polite">
            显示第 {{ page_obj.start_index }} 至 {{ page_obj.end_index }} 项结果，共 {{ paginator.count }} 项
        </div>
    </div>
    <div class="col-sm-4">
        <div class="dataTables_paginate paging_simple_numbers" id="editable_paginate">
            <ul class="pagination" style="margin-top: 0; float: right">
                {% if page_obj.has_previous %}
                    <li class="paginate_button previous" aria-controls="editable" tabindex="0" id="previous">
                        <a data-page="next" href="?page={{ page_obj.previous_page_number }}">‹</a>
                    </li>
                {% endif %}

                {% for page in paginator.num_pages %}
                    {% if page == page_obj.number %}
                        <li class="paginate_button active" aria-controls="editable" tabindex="0">
                            {% else %}
                        <li class="paginate_button" aria-controls="editable" tabindex="0">
                    {% endif %}
                <a class="page" href="?page={{ page }}" title="第{{ page }}页">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="paginate_button next" aria-controls="editable" tabindex="0" id="next">
                        <a data-page="next" href="?page={{ page_obj.next_page_number }}">›</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endif %}
<script>
    $(document).ready(function () {
        $('.page').click(function () {
            var searchStr = location.search;
            var old_href = $(this).attr('href').replace('?', '');
            var searchArray = searchStr.split('&');

            if (searchStr == '') {
                searchStr = '?page=1'
            }

            if (searchStr.indexOf('page') >= 0) {
                searchArray.pop();
            }

            searchArray.push(old_href);
            if (searchArray.length > 1) {
                $(this).attr('href', searchArray.join('&'));
            }
        })
    });

</script>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MQ管理平台</title>
    <link rel="shortcut icon" href="{% static 'img/facio.ico' %}" type="image/x-icon">
    {% include '_head_css_js.html' %}
    {% block custom_head_css_js %} {% endblock %}
</head>

<body>
<div id="wrapper">
    {% include '_left_side_bar.html' %}
    <div id="page-wrapper" class="gray-bg dashbard-1">
        {% include '_header_bar.html' %}
        {% include '_message.html' %}
        {% block help_message %} {% endblock %}
        {% block content %}{% endblock %}
        {% include '_footer.html' %}
    </div>
</div>

{% include '_foot_js.html' %}
{% block custom_foot_js %} {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}}
{% load common_tags %}
{% block content %}
    <!--页面顶部消息提醒-->
    <div class="wrapper wrapper-content">
        {% if error %}
            <div class="alert alert-warning text-center">{{ error }}</div>
        {% endif %}
        {% if msg %}
            <div class="alert alert-success">{{ msg | safe }}</div>
        {% endif %}

        <!--汇总统计-->
        <div class="row">
            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <span class="label label-danger pull-right">系统管理员</span>
                        <h5>Admin</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins"><a href="{% url 'users:user-list' %}">
                            {{ admins_count }}</a></h1>
                        <small>All admin</small>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <span class="label label-warning pull-right">队列管理员</span>
                        <h5>Operator</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins"><a href="{% url 'users:user-list' %}">
                            {{ operators_count }}</a></h1>
                        <small>All operator</small>
                    </div>
                </div>
            </div>


            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <span class="label label-info pull-right">MQ集群</span>
                        <h5>Cluster</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins"><a href="{% url 'mq:cluster-list' %}">{{ cluster_count }}</a>
                        </h1>
                        <small>All Cluster</small>
                    </div>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <span class="label label-primary pull-right">操作数</span>
                        <h5>Operate</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins"><a href="{% url 'mq:audit-log' %}"> <span
                                id="views"></span>{{ today_operate }}</a></h1>
                        <small>All Operate</small>
                    </div>
                </div>
            </div>

            <!--分析图表-->
            {% for k,v in mq_cluster_overview.items %}
                <div class="row" style="padding-left:5px;padding-right:5px;">
                    <div class="ibox float-e-margins">
                        <!--图表头部开始-->
                        <div class="ibox-title">
                            <h5>{{ k | env_name }} {% for context in v.contexts %}
                                <a class="btn btn-xs btn-info">{{ context.ip }}</a>{% endfor %}</h5>
                        </div>
                        <!--图表内容开始-->
                        <div class="ibox-content">
                            <div class="row border-bottom dashboard-header">
                                <div class="col-md-3">
                                    <table class="table table-striped table-bordered table-hover no-footer">
                                        <tbody>
                                        {% for m,n in v.object_totals.items %}
                                            <tr>
                                                <td class="text-navy">{{ m|msg_translate }}</td>
                                                <td>{{ n }}</td>
                                            </tr>
                                        {% endfor %}
                                        <tr>
                                            <td class="text-navy">消息总量</td>
                                            <td>{{ v.queue_totals.messages }}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-8">
                                    <table class="table table-striped table-bordered table-hover no-footer">
                                        <thead>
                                        <tr class="text-navy">
                                            <td align="center">节点名称</td>
                                            <td align="center">文件描述符</td>
                                            <td align="center">管道描述符</td>
                                            <td align="center">Erlang进程</td>
                                            <td align="center">内存</td>
                                            <td align="center">磁盘</td>
                                            <td align="center">节点信息</td>
                                            <td align="center">IO写统计</td>
                                            <td align="center">运行中</td>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for node in v.node_info %}
                                            <tr>
                                                <td align="center">{{ node.name }}</td>
                                                <td align="center">{{ node.fd_used }}/{{ node.fd_total }}</td>
                                                <td align="center">{{ node.sockets_used }}/{{ node.sockets_total }}</td>
                                                <td align="center">{{ node.proc_used }}/{{ node.proc_total }}</td>
                                                <td align="center">{{ node.mem_used |byte_to_mb }}MB/{{ node.mem_limit |byte_to_mb }}MB</td>
                                                <td align="center">{{ node.disk_free |byte_to_gb }}GB</td>
                                                <td align="center">{{ node.type }}</td>
                                                <td align="center">{{ node.io_write_count }}</td>
                                                <td align="center">
                                                    {% if node.running %}
                                                        <i class="fa fa-check text-navy"></i>
                                                    {% else %}
                                                        <i class="fa fa-circle text-danger"></i>
                                                    {% endif %}
                                                </td>
                                            </tr>

                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}