mqmanager/urls.py
from django.conf.urls import url, include, handler404, handler500
from .views import dashboard, page_not_found, page_error, permission_denied

# from django.contrib import admin
urlpatterns = [
    # dashboard
    url(r'^$', dashboard, name='dashboard'),

    # mq
    url(r'^mq/', include("rabbitmq.urls")),
    url(r'^users/', include("users.urls")),
]

handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

users/urls.py
from django.conf.urls import url
from .views import *

app_name = 'users'

urlpatterns = [
    # Login
    url(r'^login$', user_login, name='user-login'),
    url(r'^logout$', user_logout, name='user-logout'),

    # User
    url(r'^user$', user_list, name='user-list'),
    url(r'^user/create$', user_create, name='user-create'),
    url(r'^user/delete', user_delete, name='user-delete'),
    #url(r'^user/delete$', user_logout, name='user-list'),

    # Profile
    url(r'^profile/$', user_profile, name='user-profile'),
]

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
import uuid


# Create your models here.


class User(AbstractUser):
    ROLE_ADMIN = 'Admin'
    ROLE_OPERATOR = 'Operator'
    ROLE_USER = 'User'

    ROLE_CHOICES = (
        (ROLE_ADMIN, '超级管理员'),
        (ROLE_OPERATOR, '队列管理员'),
        (ROLE_USER, '普通用户')
    )
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=128, null=True, verbose_name='姓名')
    # avatar = models.ImageField(upload_to="avatar", null=True, verbose_name='头像')
    wechat = models.CharField(max_length=128, null=True, verbose_name='微信')
    phone = models.CharField(max_length=20, null=True, verbose_name='手机')
    date_expired = models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')
    created_by = models.CharField(max_length=30, default='', verbose_name='创建者')
    role = models.CharField(choices=ROLE_CHOICES, default=ROLE_USER, max_length=10,
                            verbose_name='用户角色')
    comment = models.TextField(max_length=200, null=True, verbose_name='备注')

    def __str__(self):
        return self.name

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404
from mqmanager.common import require_role, ServerError
# Create your views here.
from .models import *

from django.db.models import Q


def user_login(request):
    """登录界面"""
    context = {}
    if request.method == 'GET':
        return render(request, 'users/login.html')
    else:
        next_url = request.GET.get('next')
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # login log
                    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', '').split(',')
                    if x_forwarded_for and x_forwarded_for[0]:
                        login_ip = x_forwarded_for[0]
                    else:
                        login_ip = request.META.get('REMOTE_ADDR', '')
                    user_agent = request.META.get('HTTP_USER_AGENT', '')
                    # write_login_log(request.user.username, ip=login_ip, user_agent=user_agent)
                    if next_url:
                        return HttpResponseRedirect(next_url)
                    else:
                        return HttpResponseRedirect(reverse('dashboard'))
            else:
                context['error'] = '用户名或密码错误'
    return render(request, 'users/login.html', locals())


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:user-login'))


@login_required
def user_profile(request):
    app, action = '用户', '用户资料'
    user_id = request.user.id
    if not user_id:
        return HttpResponseRedirect(reverse('users:user_login'))
    return render(request, 'users/user_profile.html', locals())


@require_role(role='user')
def user_list(request, **kwargs):
    app, action = '用户', '用户列表'
    user_list = User.objects.all()
    return render(request, 'users/user_list.html', locals())


@require_role(role='admin')
def user_create(request):
    app, action = '用户', '创建用户'
    if request.method == 'GET':
        groups_selected = []
        return render(request, 'users/user_create_update.html', locals())

    if request.method == 'POST':
        username = request.POST.get('username', '')
        email = request.POST.get('email', '')
        name = request.POST.get('name', '')
        role = request.POST.get('role', '')
        new_password = request.POST.get('new_password', '')
        verify_password = request.POST.get('verify_password', '')
        is_active = request.POST.get('is_active', '')
        try:
            if '' in [username, email, name, new_password, verify_password]:
                error = '带*内容不能为空'
                raise ServerError(error)
            if User.objects.filter(username=username):
                error = '用户名：%s 已存在' % username
                raise ServerError(error)
            if username in ['root', 'admin', 'administrator', 'superuser']:
                error = '用户名不能为: %s' % username
                raise ServerError(error)
            # if not re.match(r"^[A-Z,a-z][A-Z,a-z,0-9,_-]{4-16}$", username):
            #    error = '用户名不合法,用户名只可使用[a-z,A-Z,0-9,_-]中的字符,长度位4-16位'
            #    raise ServerError(error)
            if not (new_password == verify_password):
                error = '两次输入的密码不一致，请重新输入。'
                raise ServerError(error)
        except ServerError:
            pass
        else:
            user = User.objects.create(username=username, email=email, name=name,role=role,
                                       is_active=is_active)
            user.set_password(verify_password)
            user.save()
            msg = '添加用户成功'

    return render(request, 'users/user_create_update.html', locals())


@require_role(role='admin')
def user_delete(request):
    if request.method == "GET":
        user_id = request.GET.get('id', '')
        User.objects.filter(id=user_id).delete()
    return HttpResponseRedirect(reverse('users:user-list'))

templates/users/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 登录 | MQ管理平台 </title>
    <link rel="shortcut icon" href="/static/img/facio.ico" type="image/x-icon">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
</head>

<body class="gray-bg">
<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        <div>
            <h1 class="logo-name"><img src="/static/img/logo-mq.png"></h1>
        </div>
        {% if error %}
            <div class="alert alert-danger text-center">{{ error }}</div>
        {% endif %}
        <h2>MQ管理平台</h2>
        {% if context.error %}
            <div class="alert alert-danger text-center">{{ context.error }}</div>
        {% endif %}
        <form class="m-t" role="form" method="post" action="">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="username" class="form-control" placeholder="Username"
                       required="length[6~50]">
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Password"
                       required="">
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">Login</button>
        </form>
        <p class="m-t">
            <strong>Copyright</strong> MQ管理平台 &copy; 2014-2018
        </p>
    </div>
</div>

<!-- Mainly scripts -->
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>

</body>

</html>

templates/users/user_create_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>创建用户</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form method="post" id="userForm" class="form-horizontal" action="">
                            {% csrf_token %}
                            {% if error %}
                                <div class="alert alert-warning text-center">{{ error }}</div>
                            {% endif %}
                            {% if msg %}
                                <div class="alert alert-success">{{ msg | safe }}</div>
                            {% endif %}
                            <h3>账号</h3>
                            <div class="form-group">
                                <label for="username" class="col-sm-2 control-label">用户名<span
                                        class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="username" name="username" placeholder="请输入用户名" type="text"
                                           class="form-control" {% if error %}value="{{ username }}" {% endif %}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-sm-2 control-label">邮箱<span
                                        class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="email" name="email" type="email" placeholder="请输入邮箱"
                                           class="form-control" {% if error %}value="{{ email }}" {% endif %}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">姓名<span
                                        class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="name" name="name" placeholder="请输入姓名" type="text" class="form-control"
                                           {% if error %}value="{{ name }}" {% endif %}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="role" class="col-sm-2 control-label">角色</label>
                                <div class="col-sm-8">
                                    <select name="role" class="form-control">
                                        <option value="User" selected>普通用户</option>
                                        <option value="Operator">队列管理员</option>
                                        <option value="Admin">系统管理员</option>
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <h3>安全</h3>
                            <div class="form-group">
                                <label for="new_password" class="col-sm-2 control-label">输入密码<span
                                        class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="new_password" name="new_password" placeholder="输入密码" type="password"
                                           class="form-control"
                                           {% if error %}value="{{ new_password }}" {% endif %}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="verify_password" class="col-sm-2 control-label">重复密码<span
                                        class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="verify_password" name="verify_password" placeholder="再次输入密码"
                                           type="password"
                                           class="form-control"
                                           {% if error %}value="{{ verify_password }}" {% endif %}>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <h3>其它</h3>
                            <div class="form-group"><label class="col-sm-2 control-label">其它</label>
                                <div class="col-sm-2">
                                    <div class="checkbox i-checks">
                                        <label><input name="is_active" type="hidden" value="False">
                                            <input name="is_active" type="checkbox" value="True" id="is_active"
                                                   checked="checked">
                                            启用账号 </label>
                                    </div>
                                </div>
                                <!--
                                <div class="col-sm-2">
                                    <div class="checkbox i-checks">
                                        <label><input type="checkbox" value="0" name="extra">发送邮件 </label>
                                    </div>
                                </div>
                                -->
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="reset">取消</button>
                                    <button id="submit_button" class="btn btn-primary" type="submit">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}%

templates/users/user_list.html
{% extends '_base_list.html' %}

{% block help_message %}
    <div class="alert alert-info help-message">
        <p>{{ action }}是 该管理平台中所管理的用户</p>
    </div>
{% endblock %}

{% block table_head %}
    <td class="text-center">用户名</td>
    <td class="text-center">姓名</td>
    <td class="text-center">邮箱</td>
    <td class="text-center">角色</td>
    <td class="text-center">启用</td>
    <td class="text-center">操作</td>
{% endblock %}
{% block table_body %}
    {% for user in user_list %}
        <tr>
            <td class="text-center">{{ user.username }}</td>
            <td class="text-center">{{ user.name }}</td>
            <td class="text-center">{{ user.email }}</td>
            <td class="text-center">
                {% if user.role == 'Admin' %}
                    <a class="btn btn-xs btn-danger">系统管理员</a>
                {% elif user.role == 'Operator' %}
                    <a class="btn btn-xs btn-warning">队列管理员</a>
                {% else %}
                    <a class="btn btn-xs btn-info">普通用户</a>
                {% endif %}
            </td>
            <td class="text-center">
                {% if user.is_active %}
                    <i class="fa fa-check text-navy"></i>
                {% else %}
                    <i class="fa fa-circle text-danger"></i>
                {% endif %}
            </td>
            <td class="text-center">
                <a href="{% url 'users:user-delete' %}?id={{ user.id }}"
                   class="btn btn-xs btn-danger {% if request.user.role != 'Admin' %}disabled{% endif %}">删除</a></td>
        </tr>
    {% endfor %}

{% endblock %}
{% block custom_foot_js %}
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                //dom: '<"html5buttons"B>lTfgitp',
                //dom: '<"html5buttons"B><"top"f>rt<"bottom"pli><"clear">',
                dom: 'Blfrtip',
                buttons: [
                    {% if request.user.role == 'Admin' %}
                        {
                            text: '添加用户', action: function (e, dt, button, config) {
                                window.location = '{% url 'users:user-create' %}';
                            }
                        },
                    {% endif %}
                    {extend: 'copy', text: '复制到剪贴板', title: '用户列表'},
                    {extend: 'csv', text: '导出CSV', title: '用户列表'},
                    {extend: 'excel', text: '导出EXCEL', title: '用户列表'},
                ], "oLanguage": { // 国际化配置
                    "sProcessing": "正在获取数据，请稍后...",
                    "sLengthMenu": "显示 _MENU_ 条",
                    "sZeroRecords": "没有找到数据",
                    "sInfo": "从 _START_ 到  _END_ 条记录 总记录数为 _TOTAL_ 条",
                    "sInfoEmpty": "记录数为0",
                    "sInfoFiltered": "(全部记录数 _MAX_ 条)",
                    "sInfoPostFix": "",
                    "sSearch": "搜索",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "第一页",
                        "sPrevious": "上一页",
                        "sNext": "下一页",
                        "sLast": "最后一页"
                    }
                }

            });

        });
    </script>
{% endblock %}

templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block custom_head_css_js %}
    <link href="{% static "css/plugins/sweetalert/sweetalert.css" %}" rel="stylesheet">
    <script src="{% static "js/plugins/sweetalert/sweetalert.min.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="" class="text-center"><i class="fa fa-laptop"></i> 查看资料 </a>
                            </li>
                            <li class="pull-right">
                                <a class="btn btn-outline btn-default" href="/}"><i
                                        class="fa fa-edit"></i>更改资料</a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="col-sm-7" style="padding-left: 0;">
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <span class="label label-primary"><b>{{ request.user }}</b></span>
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>
                                        <a class="close-link">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="ibox-content">
                                    <div class="text-left">
                                        <table class="table">
                                            <tr class="no-borders-tr">
                                                <td colspan="2">
                                                    <img src="/static/img/avatar/admin.png" class="img-circle"
                                                         width="64"
                                                         height="64">
                                                </td>
                                            </tr>
                                            <tr class="no-borders-tr">
                                                <td class="text-navy">用户名</td>
                                                <td>{{ request.user }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-navy">姓名</td>
                                                <td>{{ request.user.name }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-navy">邮箱</td>
                                                <td>{{ request.user.email }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-navy">角色</td>
                                                {% if request.user.role == 'Admin' %}
                                                    <td>系统管理员</td>
                                                {% elif request.user.role == 'Operator' %}
                                                    <td>队列管理员</td>
                                                {% else %}
                                                    <td>普通用户</td>
                                                {% endif %}
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5" style="padding-left: 0;padding-right: 0">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <i class="fa fa-info-circle"></i> 快速修改
                            </div>
                            <div class="panel-body">
                                <table class="table">
                                    <tbody>
                                    <tr class="no-borders-tr">
                                        <td>重置密码:</td>
                                        <td>
                                            <span class="pull-right">
                                                <a type="button" class="btn btn-primary btn-xs" style="width: 54px"
                                                   href="#">重置</a>
                                            </span>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}